const students = [
{ name: "RASYFA NADYA PUTERI" , id: "001" },	
{ name: "MUHAMMAD DZAKWAN" , id: "002" },
{ name: "M. FAQIH PRASETYO" , id: "003" },
{ name: "M. LUTHFI APRIANSYAH" , id: "004" },
{ name: "NURI AYUNI" , id: "005" },
{ name: "ANDI ARIF" , id: "006" },
{ name: "M. HAIKAL FIRDAUS" , id: "007" },
{ name: "AHSANUL DANISH SETIAWAN" , id: "008" },
{ name: "M. RAIHAN ABDILLAH" , id: "009" },
{ name: "DHEANETA PUTRI AZZAHRA TANJUNG" , id: "010" },
{ name: "AHMAD MAHER ADIB" , id: "011" },
{ name: "AHMAD RAFIQ" , id: "012" },
{ name: "AJENG FAKHIRA SYAKILA" , id: "013" },
{ name: "AKHMAD RADITYA AGZA" , id: "014" },
{ name: "ANINDYA NURRAHMAYANTI" , id: "015" },
{ name: "ARIAN MAHENDRA DINATA" , id: "016" },
{ name: "BILQIZ AMANDA APRILLIA" , id: "017" },
{ name: "FERDI SETIAWAN" , id: "018" },
{ name: "GITA NADHIRA MUZDHALIFAH" , id: "019" },
{ name: "HAFIZAH" , id: "020" },
{ name: "MARITZA ANANDA WINOV" , id: "021" },
{ name: "MIRZHA ACHMAD HAMIZAN" , id: "022" },
{ name: "MUHAMMAD ABID RAFIQI" , id: "023" },
{ name: "MUHAMMAD DHAFIN ALFARIZI IDRIS" , id: "024" },
{ name: "MUHAMMAD RAID AL FADHIL" , id: "025" },
{ name: "NADHIF RAIHAN ANNAFIS" , id: "026" },
{ name: "NAURA GANES PARAMESWARI" , id: "027" },
{ name: "NIZAR FAZARI" , id: "028" },
{ name: "RAYSA ARIAYANI" , id: "029" },
{ name: "RUMAISHA AUFA RIFQOH HIDAYAH" , id: "030" },
{ name: "SELVIA AMELIA" , id: "031" },
{ name: "AHMAD FARI BREGA SALEH" , id: "032" },
{ name: "ARDIONA BRATAJAYA" , id: "033" },
{ name: "ARMAND MAULANA" , id: "034" },
{ name: "NAILATUL HASANAH" , id: "035" },
{ name: "FATHIR ILMAN FADHILAH" , id: "036" },
{ name: "SYARIFAH AMINAH HUMAIRA" , id: "037" },
{ name: "MUHAMMAD RAFA PRATAMA" , id: "038" },
{ name: "MUHAMMAD RAIFAN MAULANA IDRIS" , id: "039" },
{ name: "MUHAMMAD DANISH" , id: "040" },
{ name: "NUR WAFA AZIZAH" , id: "041" },
{ name: "NUR IZZA KAMILIA" , id: "042" },
{ name: "AVIQAH NUR INDAH" , id: "043" },
{ name: "ADIBA  SYAHLA SAKILA" , id: "044" },
{ name: "AULIA NUR RAMADHINI" , id: "045" },
{ name: "QAISHA ANNISA" , id: "046" },
{ name: "MUTIARA OKTA BARLIYANTI NINGSIH" , id: "047" },
{ name: "NUR KEISHA HUMAIRA" , id: "048" },
{ name: "RAISYA SABILA MUSAKINA" , id: "049" },
{ name: "SYARIFAH NAFIISAH" , id: "050" },
{ name: "ZAHIDA QOLBI NADHIFA" , id: "051" },
{ name: "ZAHRA NUR ISTIQOMAH" , id: "052" },
{ name: "AFFAN" , id: "053" },
{ name: "M. HAFIDZ RAMDHAN" , id: "054" },
{ name: "M. REVANI ALRUS" , id: "055" },
{ name: "M. FATTAN AL-GHIFARI" , id: "056" },
{ name: "MUHAMMAD FAUZI" , id: "057" },
{ name: "M. RAIHAN HAFIDZ" , id: "058" },
{ name: "M. ZAKI FATURRAHMAN" , id: "059" },
{ name: "ALAYYA AFSHEEN HUMAIRA" , id: "060" },
{ name: "ADELIA APRISA" , id: "061" },
{ name: "ADILA KHUMAIRA" , id: "062" },
{ name: "ALIFIANDRA PRANAJA KURNIAWAN" , id: "063" },
{ name: "ANDI EARLYTA SALSABILA" , id: "064" },
{ name: "AQILA KHAIRINA" , id: "065" },
{ name: "BAHID LINDAN NUGROHO" , id: "066" },
{ name: "M. DIMAS ALFIANNOR" , id: "067" },
{ name: "MUHAMMAD NAZIB" , id: "068" },
{ name: "NABILA AZZAHRA" , id: "069" },
{ name: "NUR MAULIDA ZAHRA" , id: "070" },
{ name: "NUR NAAILA NABIHAH" , id: "071" },
{ name: "QUR'RATU A'INUN" , id: "072" },
{ name: "RAFASYA ALHADDA" , id: "073" },
{ name: "REGHITA CAHAYA ARUMI" , id: "074" },
{ name: "MUHAMMAD SYARWANI ABDAN" , id: "075" },
{ name: "NAISYA NUR LATIFA" , id: "076" },
{ name: "RAFIF GISWA ALVARO" , id: "077" },
{ name: "M. AZKA MAULANA" , id: "078" },
{ name: "NABIL KHAIRAN" , id: "079" },
{ name: "FEBRYANA SANDI NAURA" , id: "080" },
{ name: "LUBNA AZZAHRA" , id: "081" },
{ name: "ADEBA RAMADHAYANTI" , id: "082" },
{ name: "AMIRAIFA SAJIDA" , id: "083" },
{ name: "AZZAM INSANI" , id: "084" },
{ name: "FARAH AZKIA" , id: "085" },
{ name: "HESTY SALSABILA PUTRI" , id: "086" },
{ name: "MUHAMMAD SALMAN" , id: "087" },
{ name: "NABILA MUFARIHANA" , id: "088" },
{ name: "NUR AULIA" , id: "089" },
{ name: "NUR EKA PRATIWI" , id: "090" },
{ name: "QUEENA RAIHANA YASMINE" , id: "091" },
{ name: "QYARA ALIFAH AZZAHRA" , id: "092" },
{ name: "SYAFIYA RAHMA" , id: "093" },
{ name: "ALIKA AZKADINA" , id: "094" },
{ name: "DWI SATRIO WIBOWO" , id: "095" },
{ name: "HIKMAL AHMAD" , id: "096" },
{ name: "M. ZULFI ALFAR" , id: "097" },
{ name: "M. SUMARDIANSYAH" , id: "098" },
{ name: "MAYA DWI PRATIWI" , id: "099" },
{ name: "MUHAMMAD ABDILLLAH" , id: "100" },
{ name: "MUHAMMAD AIDIL ALVANDI RAJA" , id: "101" },
{ name: "MUHAMMAD AMMAR ALFARIZI" , id: "102" },
{ name: "MUHAMMAD HAIKAL (A)" , id: "103" },
{ name: "MUHAMMAD LATHIIFU ROHIM" , id: "104" },
{ name: "MUHAMMAD MUJADDID" , id: "105" },
{ name: "MUHAMMAD RIDHO" , id: "106" },
{ name: "MUHAMMAD UWAYS ATIN'NA" , id: "107" },
{ name: "ZAHWA AQILA RAMADHANI" , id: "108" },
{ name: "NUR HIDAYATI" , id: "109" },
{ name: "AHMAD FARIS FATHULLAH" , id: "110" },
{ name: "FATIMAH ATIKAH AMIRA" , id: "111" },
{ name: "GUSTI MUHAMMAD ILYASA" , id: "112" },
{ name: "HALIZA ALIQA PUTRI" , id: "113" },
{ name: "M. RIDWAN" , id: "114" },
{ name: "MUHAMMAD KHAIRUL AZMI" , id: "115" },
{ name: "MUHAMMAD MUFTHI RAYKHAL" , id: "116" },
{ name: "MUHAMMAD SULTAN KITA MARLY" , id: "117" },
{ name: "MUHAMMAD YUSUF RIZQI ARIFFADLY" , id: "118" },
{ name: "NUR ALYA NATASYA" , id: "119" },
{ name: "ORLIN CAHAYA WINOV" , id: "120" },
{ name: "RAIHAN MUZAKKI" , id: "121" },
{ name: "ZIHAN FAJIRA SALSABILA" , id: "122" },
{ name: "LUCKY VITO NAFIS" , id: "123" },
{ name: "AZZIRA NAFITA" , id: "136" },
{ name: "ADIBA NAIMA FATINA" , id: "137" },
{ name: "DEFINA DWI YUNIARTI" , id: "138" },
{ name: "KENZIE ARGA PRADANA ADITYA" , id: "139" },
{ name: "AISYAH HUMAIRA" , id: "140" },
{ name: "AISYAH AFIQAH" , id: "141" },
{ name: "RAZIN DWIKI RAMADHAN" , id: "142" },
{ name: "KHOIRUL ANWAR" , id: "143" },
{ name: "MUHAMMAD ABIZHAR AI-GHIFARI" , id: "144" },
{ name: "KAYLA APRILIA MUTIARA SABILA" , id: "145" },
{ name: "MEDINA  RISCA A.D" , id: "146" },
{ name: "NAJWA DELIANA NAUFAL KURNIA" , id: "147" },
{ name: "NUR AISYAH AQILA" , id: "148" },
{ name: "QAIREEN MUFTHIA AR RAYYA" , id: "149" },
{ name: "MUHAMMAD NABIEL" , id: "150" },
{ name: "RUHAMA AFIFA" , id: "151" },
{ name: "ANINDITA KHAIRINNISWA" , id: "152" },
{ name: "GUSTI HAIKAL RIZA ADITYA" , id: "153" },
{ name: "ZIA ATHIFA ALIYA" , id: "154" },
{ name: "AHMAD NAUFAL RAFIANDRA" , id: "155" },
{ name: "ADITYA SHAKIL MUHARRAM" , id: "156" },
{ name: "MUHAMMAD NOR SAHAL" , id: "157" },
{ name: "ACHMAD AZZAM RAJENDRA" , id: "158" },
{ name: "ALEEYA QUINSHA AZZAHRA" , id: "159" },
{ name: "ZEIN AEZAR VIFAN" , id: "160" },
{ name: "MUHAMMAD ABIZAR RAMADHAN" , id: "161" },
{ name: "ADYATMA AGRA AFFANDI" , id: "162" },
{ name: "ALISYA KHAIRA WILDA" , id: "163" },
{ name: "MUHAMMAD ARRAFI" , id: "164" },
{ name: "MUHAMMAD IQBAL ARYANI" , id: "165" },
{ name: "AHMAD RAFFI" , id: "166" },
{ name: "ERLANGGA BAGAS KHAIRULANAM" , id: "167" },
{ name: "ERLANGGA BAGUS KHAIRULANAM" , id: "168" },
{ name: "KAYYISA NUR NADZIFA" , id: "169" },
{ name: "M. KHAIRUL ANAM" , id: "170" },
{ name: "M. RIZKY AZKA RAYYAN" , id: "171" },
{ name: "MUAMMAR FAIZ JAWAN" , id: "172" },
{ name: "MUHAMMAD RAMADAN" , id: "173" },
{ name: "NUR NAYLA" , id: "174" },
{ name: "AFNAN PAISAL RAHMAN" , id: "175" },
{ name: "MUHAMMAD KHAIRUL WAFA" , id: "176" },
{ name: "ANDI AUFA" , id: "177" },
{ name: "INTAN WULANDARI" , id: "178" },
{ name: "KEISHA ADILA OKTAVIANA" , id: "179" },
{ name: "KINANTHI ARIANNA FATIMA" , id: "180" },
{ name: "M. BAIHAQI" , id: "181" },
{ name: "NURUL AZKIYA AS SYIFA" , id: "182" },
{ name: "RAHMAT ALAMSYAH PUTRA" , id: "183" },
{ name: "RAMADHAN ALAMSYAH PUTRA" , id: "184" },
{ name: "MUHAMMAD VIRZA ABQARI IDRIS" , id: "185" },
{ name: "SABRINA AZZAHRA" , id: "186" },
{ name: "MUHAMMAD FARIS AF. RAZZAQ" , id: "187" },
{ name: "NAYYARA HAFIZAH" , id: "188" },
{ name: "ARYA JAKA SAPUTRA" , id: "189" },
{ name: "AHMAD RAFKA AL GHIFARI" , id: "190" },
{ name: "MONA FAIQAH RAMADHANI" , id: "191" },
{ name: "LISA SARASVATI SALSABILA" , id: "192" },
{ name: "BAIHAKKI FINO KHAIRAN" , id: "193" },
{ name: "ANDI MUHAMMAD RAFA ILYASA" , id: "194" },
{ name: "MUHAMMAD ARKANA LATIEF AL FATIH" , id: "195" },
{ name: "M. ALVIN FAIZ" , id: "196" },
{ name: "FAUZAN" , id: "197" },
{ name: "APRILIA AL JANNATA" , id: "198" },
{ name: "RAFA RAYYA MAULANA" , id: "199" },
{ name: "AHMAD AKBAR" , id: "200" },
{ name: "M. ZAKY FAHREZA" , id: "201" },
{ name: "M. ABIZARD ARIFIN" , id: "202" },
{ name: "M.ZAKY AL HAFIZI" , id: "203" },
{ name: "M. ABYZAR AL GHIFARI" , id: "204" },
{ name: "M. ZAKY RIZALI" , id: "205" },
{ name: "RINDU ΑΤΙQΑ ΑNANDA" , id: "206" },
{ name: "RIZKI SHERLIYATI" , id: "207" },
{ name: "REGHINA JASMIN ANGGRAINI" , id: "208" },
{ name: "NADHIRA NUR FATIMAH" , id: "209" },
{ name: "MURAISYA" , id: "210" },
{ name: "KHAIRUNAFISYA" , id: "211" },
{ name: "SYIFA ADILA " , id: "212" },
{ name: "SHAQUENA" , id: "213" },
{ name: "RADYFA ARVA DINATA" , id: "214" },
{ name: "ALINA MARYAM ARUMINGRATRI" , id: "215" },
{ name: "FACHRAISA NAYYRA SAFFANA" , id: "216" },
{ name: "BAYU PRIMA PRAYOGA" , id: "217" },
{ name: "ANUGRAH PUTRA WAHYU PERDANA" , id: "218" },
{ name: "M. RIAN HERNANDI" , id: "219" },
{ name: "NABIZAR AL GHAZALI" , id: "220" },
{ name: "NADIRA RIZKY WINATA" , id: "221" },
{ name: "HERLIA ARSYILA AZZAHRA" , id: "222" },
{ name: "AISYAH AZKIA" , id: "223" },
{ name: "DAISYAH CARRISA ANWAR" , id: "224" },
{ name: "ADILA HUSNA SYAKILA" , id: "225" },
{ name: "SILVIA AZIZAH" , id: "226" },
{ name: "MUHAMMAD NAFIS FAEZA" , id: "227" },
{ name: "LUTFI FADHIL AMMAR" , id: "228" },
{ name: "DIMAS ABYASA" , id: "229" },
{ name: "MUHAMMAD ABIZHAR AL QHIFARI" , id: "230" },
{ name: "MUHAMMAD IRJUNA RASYA PRATAMA PUTRA" , id: "231" },
{ name: "FADYA AIRA ALTAFUNNISA" , id: "232" },
{ name: "MUHAMMAD ADFAL AL-FARIZ" , id: "233" },
{ name: "MUHAMMAD RIZQI HAMIZAN" , id: "234" },
{ name: "MUHAMMAD HAFIDZ ANSHORI" , id: "235" },
{ name: "MUHAMMAD RASYIIDU SUHENDAR" , id: "236" },
{ name: "MUHAMMAD ROBY SETIAWAN" , id: "237" },
{ name: "MUHAMMAD IQBAL" , id: "238" },
{ name: "ADINDA KEISHA AZZAHRA" , id: "239" },

];

const tableBody = document.getElementById('table-body');
const searchInput = document.getElementById('search-input');

function renderTable(data) {
  tableBody.innerHTML = '';
  data.forEach(student => {
    const row = `<tr>
      <td>${student.id}</td>
      <td>${student.name}</td>
    </tr>`;
    tableBody.innerHTML += row;
  });
}

function filterStudents(query) {
  return students.filter(student =>
    student.name.toLowerCase().includes(query.toLowerCase())
  );
}

searchInput.addEventListener('input', (e) => {
  const filteredStudents = filterStudents(e.target.value);
  renderTable(filteredStudents);
  tableBody.classList.toggle('hidden', e.target.value.length === 0);
});

// Initial state: table is hidden
tableBody.classList.add('hidden');
